import mongoose from "mongoose";
const productSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      minlength: [3, "Name must be at least 3 characters long."],
      maxlength: [50, "Name cannot exceed 50 characters."],
      required: [true, "Name is required!"],
    },
    description: {
      type: String,
      minlength: [10, "Description must be at least 10 characters long."],
      required: [true, "Description is required!"],
    },
    price: { type: Number, min: 0, required: [true, "Price is required!"] },
    image: { type: String, required: [true, "Image is required!"] },
    category: { type: String, required: [true, "Category is required!"] },
    isFeatured: { type: Boolean, default: false },
    // ✅ Store the Cloudinary public_id for reliable deletion
    // ✅ publicId should NOT be required since it's generated by Cloudinary
    publicId: { type: String },

    // ✅ Add a stock field for inventory management
    stock: { type: Number, min: 0, default: 0 },
  },

  { timestamps: true }
);
const Product = mongoose.model("Product", productSchema);
export default Product;
